### ISSUE TITLE
how do i start using this in my code?

### ISSUE THREAD

**Issue by LancerLunatic** [JeremyLinux/PyTorch-Radial-Basis-Function-Layer#2]
Hi i'm glad i found this RBF implementation. thanks for writing it. Here's my linear model prediction so far. how do start using yours?

class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)   # hidden layer
        self.predict = torch.nn.Linear(n_hidden, n_output)   # output layer
    
    def forward(self, x):
        x = F.relu(self.hidden(x))      # activation function for hidden layer
        x = self.predict(x)             # linear output
        return x

**Comment by JeremyLinux** [comment]
The approximate equivalent of a neural network with one hidden layer would be something like this. One hidden (rbf) layer and then a linear output layer.

```
import torch.nn as nn
import torch_rbf as rbf

class MyRBFNetwork(nn.Module):

    def __init__(self, n_feature, n_hidden, n_output):
        super(MyRBFNetwork, self).__init__()
        self.hidden = rbf.RBF(n_input, n_hidden, rbf.gaussian)
        self.predict = nn.Linear(n_hidden, n_output)
    
    def forward(self, x):
        x = self.hidden(x)
        x = self.predict(x)
        return x
```

You could replace rbf.gaussian with one of {rbf.linear, rbf.quadratic, rbf.inverse_quadratic, rbf.multiquadric, rbf.inverse_multiquadric, rbf.spline, rbf.poisson_one, rbf.poisson_two, rbf.matern32, rbf.matern52}, although rbf.gaussian usually works well. Alternatively, you could define your own function and use that instead of rbf.gaussian, e.g.

```
def my_func(x):
    y = some_element_wise_function(x)
    # e.g. y = torch.exp(-x)
    return y
```

The hidden layer would then be instantiated as follows.

```
self.hidden = rbf.RBF(n_input, n_hidden, my_func)
```

I hope this helps.
